# Generated by Django 5.1.1 on 2024-12-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('SCI', 'Science'), ('HIS', 'History'), ('SPT', 'Sport'), ('MTH', 'Math'), ('CMD', 'Comedy'), ('GMS', 'Games'), ('EDU', 'Education'), ('OTH', 'Other')], default='OTH', max_length=20),
        ),
    ]
