# Generated by Django 5.1.1 on 2024-12-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_create', '0002_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
