# Generated by Django 5.1.1 on 2024-12-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('correct_answer', models.CharField(max_length=20)),
                ('incorrect1', models.CharField(max_length=20)),
                ('incorrect2', models.CharField(max_length=20)),
                ('incorrect3', models.CharField(max_length=20)),
                ('explanation', models.TextField(max_length=50)),
            ],
        ),
    ]
