# Generated by Django 5.1.1 on 2024-12-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
